import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { motion } from "framer-motion";
import Card from "./card.js";
import Nav from "./nav";
import About from "./About.js";
import Homepage from "./honepage.js";
import AboutCard from "./AboutCard.js";
import Portofolio from "./Portofolio.js";
import LastContent from "./LastContent.js";
import Footer from "./Footer.js";


export default function Home() {
  return (
    <>
      <Head>
        <title>Hello 🖐, I&rsquo;m Fahlevi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo1.webp" />
      </Head>

      <nav>
        <Nav />
      </nav>

      <main className={styles.main}>
        <motion.div
          id="home"
          initial="offscreen"
          whileInView="onscreen"
          viewport={{ once: true, amount: 0.8 }}
        >
          <div className={styles.description}>
            <Homepage />

            <div className={styles.vercelLogo}></div>
          </div>
        </motion.div>

        <div className="h-screen px-28 max-sm:px-3">
          <motion.div id="about" className="mb-36 flex flex-wrap flex-row items-center">
            <motion.h1
              initial={{ opacity: 0, y: 100 }}
              transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="mt-20 text-4xl flex justify-start px-4 items-center
            font-bold
            "
            >
              About Me
            </motion.h1>

            <About />
          </motion.div>
      <div id="tech" className=""></div>
        </div>
      </main>
      <motion.div
        
        initial={{ opacity: 0, y: 100 }}
        transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <h1
          className="flex justify-start max-sm:px-8 p-6 px-32 text-4xl  items-center
            font-bold"
        >
          Technology
        </h1>
        <motion.div
          initial={{ opacity: 0, y: 100 }}
          transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <AboutCard />
        </motion.div>
      </motion.div>
      <motion.div
        id="porto"
        initial={{ opacity: 0, y: 100 }}
        transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="h- mt-28 mb-10 flex  flex-row flex-wrap"
      >
        <h1
          className="flex justify-start max-sm:px-8 p-6 px-32 text-4xl  items-center
            font-bold"
        >
          Portofolio
        </h1>
        <motion.div
          initial={{ opacity: 0, y: 100 }}
          transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
        </motion.div>
      </motion.div>
      <Portofolio />

      <motion.div
      id="contact"
      className="h-screen flex justify-center items-center flex-row flex-wrap"
        initial={{ opacity: 0, y: 100 }}
        transition={{ type: "spring", bounce: 0.2, duration: 1.5, delay: 0.5 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <LastContent />
      </motion.div>
      <motion.div
        initial={{ opacity: 0, y: 100 }}
        transition={{ type: "spring", bounce: 0.2, duration: 1.5 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <Footer />
      </motion.div>

    </>
  );
}
